# Generated by Django 2.1.13 on 2019-11-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='The cycle number for the season')),
                ('week', models.IntegerField(help_text='The Week number in the Cycle')),
                ('season', models.CharField(choices=[('P', 'Pre-season'), ('O', 'Orientation'), ('C', 'Competitive'), ('T', 'Taper')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the workout', max_length=31)),
                ('slug', models.SlugField(max_length=31)),
                ('exercise', models.CharField(choices=[('S', 'Swim'), ('B', 'Bike'), ('R', 'Run'), ('O', 'Other')], max_length=1)),
                ('duration', models.IntegerField(help_text='How many minutes to complete')),
                ('intensity', models.CharField(choices=[('E', 'EASY'), ('M', 'MODERATE'), ('T', 'MODERATE2HIGH'), ('H', 'HIGH')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='workout',
            field=models.ManyToManyField(to='workout.Workout'),
        ),
    ]
