# Generated by Django 2.1.13 on 2019-11-29 23:32

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkout',
            name='sequence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'exercise', 'duration']),
        ),
    ]
